BEGIN;

CREATE TABLE IF NOT EXISTS products (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY,
    store VARCHAR(100),
    name TEXT NOT NULL,
    price NUMERIC(12, 2) NOT NULL,
    currency VARCHAR(10) DEFAULT 'ARS',
    url TEXT,
    scraped_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT pk_products PRIMARY KEY (id),
    CONSTRAINT uq_products_url UNIQUE (url)
);

CREATE INDEX IF NOT EXISTS ix_products_store
    ON products (store);

CREATE INDEX IF NOT EXISTS ix_products_price
    ON products (price);

CREATE INDEX IF NOT EXISTS ix_products_scraped_at
    ON products (scraped_at);

CREATE TABLE IF NOT EXISTS users (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY,
    username VARCHAR(150) NOT NULL,
    password_hash TEXT NOT NULL,
    is_active BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT pk_users PRIMARY KEY (id),
    CONSTRAINT uq_users_username UNIQUE (username)
);

CREATE TABLE IF NOT EXISTS price_history (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY,
    product_id INTEGER NOT NULL,
    price NUMERIC(12, 2) NOT NULL,
    currency VARCHAR(10),
    recorded_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT pk_price_history PRIMARY KEY (id),
    CONSTRAINT fk_price_history_product_id_products
        FOREIGN KEY (product_id)
        REFERENCES products (id)
        ON DELETE CASCADE
);

CREATE INDEX IF NOT EXISTS ix_price_history_product_id_recorded_at
    ON price_history (product_id, recorded_at);

CREATE TABLE IF NOT EXISTS user_favorites (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY,
    user_id INTEGER NOT NULL,
    product_id INTEGER NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT pk_user_favorites PRIMARY KEY (id),
    CONSTRAINT fk_user_favorites_user_id_users
        FOREIGN KEY (user_id)
        REFERENCES users (id)
        ON DELETE CASCADE,
    CONSTRAINT fk_user_favorites_product_id_products
        FOREIGN KEY (product_id)
        REFERENCES products (id)
        ON DELETE CASCADE,
    CONSTRAINT uq_user_favorites_user_product UNIQUE (user_id, product_id)
);

CREATE INDEX IF NOT EXISTS ix_user_favorites_user_id
    ON user_favorites (user_id);

CREATE INDEX IF NOT EXISTS ix_user_favorites_product_id
    ON user_favorites (product_id);

COMMIT;
