name: Scrabby Daily Run

on:
  schedule:
    - cron: '0 10 * * *' # Se ejecuta a las 10:00 UTC (07:00 AM de Argentina)
  
  workflow_dispatch: 

jobs:
  run-bot:
    runs-on: ubuntu-latest

    steps:
      - name: Obtener código de GitHub
        uses: actions/checkout@v4
      
      - name: Construir la imagen
        run: docker build --no-cache -t scrabby-bot .
      
      - name: Iniciar Scraping
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
          GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
        run: docker run --rm -e DATABASE_URL="$DATABASE_URL" -e GEMINI_API_KEY="$GEMINI_API_KEY" scrabby-bot